### PR TITLE
Added UniTiled to tools list

### PR DESCRIPTION
**Pull request by yjaffal**

### CODE REVIEW

**Comment by bjorn** [comment]
Thanks!

Have you had some feedback yet from people who tried UniTiled?

**Comment by yjaffal** [comment]
Thanks for adding UniTiled!

Yes. One of my friends who tried it on Mac is having issue in tile index in
tmx file. He got wierd large indices (like 8 digits numbers) which causes
import to fail. Even the map opens correctly in Tiled. Any idea what causes
this?

في الأحد، ٢ سبتمبر، ٢٠١٨ ١٢:١٥ م Thorbjørn Lindeijer <
notifications@github.com> كتب:

**Comment by bjorn** [comment]
> Yes. One of my friends who tried it on Mac is having issue in tile index in
> tmx file. He got wierd large indices (like 8 digits numbers) which causes
> import to fail. Even the map opens correctly in Tiled. Any idea what causes
> this?

Ah, this must be a flipped or rotated tile. Due to the use of the higher bits for storing these states, the numbers become really big. See the [documentation about tile flipping](http://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tile-flipping) for how to deal with this in your loader.

**Comment by yjaffal** [comment]
Hey, thanks for the hint! Flipped and rotated tiles are now supported :)

**Pull request merged**
