### PR TITLE
Update Python Plugin API to support new features

### PR DESCRIPTION
**Pull request by ilanosortap**

### CODE REVIEW

**Comment by bjorn** [comment]
Just including the additional headers is enough? I would expect that you'll also need to actually define the classes to expose and which methods to expose.

Also, please include the updated generated file in your commit. `pybindgen` should not be required for building Tiled, which is why the generated file is in the repository.

**Comment by bjorn** [comment]
I've rebased your change so that PyBindGen 0.18.0 can be used to generate the `pythinbind.cpp` file. But note that adding the include files does not suffice. You will need to make additional changes as seen in PR #1867.

Do you still plan to work on this?

**Comment by ilanosortap** [comment]
I ll make the additional changes and create a pull request soon.

Regards,

Sonali Patro

Contact: 00917381809123/0097455579707

**Comment by bjorn** [comment]
@ilanosortap Shall we close this or do you think you'll still continue the work sometime?

**Comment by bjorn** [comment]
Closing this due to lack of updates.

**Pull request closed without merging**
