### PR TITLE
Fix some Chinese translations

### PR DESCRIPTION
**Pull request by endlesstravel**

### CODE REVIEW

**Comment by bjorn** [comment]
Nice, thanks! Could you reopen this pull request against the `0.17` branch, so that it could be included in the upcoming `0.17.1` release?

**Comment by endlesstravel** [comment]
Okey, however, I'm not sure how to do it. Does it mean I close this pull request until the 0.17.1 branch released , and reopen the pull request for that branch ?

**Comment by endlesstravel** [comment]
Now I'm try to do it , Is it right to do so ?

**Comment by bjorn** [comment]
That isn't how it works. :-) You'd indeed need to close and reopen the pull request, otherwise all commits from the master branch that aren't yet on the 0.17 branch are included.

However, there is no need to do this anymore since I cherry-pick your changes onto the 0.17 branch now as commit a4e6f5bc8ed50dcc03e2231d3d2a5716f718a37e.

Thanks a lot for the fixes!

**Comment by endlesstravel** [comment]
:smiley:    Tiled Map Editor is really great.  
 Glad I could help.  'shy  ⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄.  '

**Pull request closed without merging**
