### PR TITLE
Build updates to tiled-java

### PR DESCRIPTION
**Pull request by mikepthomas**
Update Tiled map schema, Java and dependency versions and file licences and ensure project can be opened and built in Eclipse

### CODE REVIEW

**Comment by bjorn** [comment]
That's great, thanks for the updates!

Only two things I'm wondering about:

* I see you've checked in some hidden (dot) files. Are you sure these should be in the repository, or does building with Eclipse depend on those?

* You've updated the copyright years for all contributors, but some of us haven't touched this library much in years. I see those years were already claiming copyright until 2017 though, so this must have slipped my attention before. Doesn't really matter much I guess.

**Comment by mikepthomas** [comment]
> I see you've checked in some hidden (dot) files. Are you sure these should be in the repository, or does building with Eclipse depend on those?

Eclipse doesn't depend on them per se, however they do hold project information just like nbactions.xml for NetBeans or libtiled-java.iml for IntelliJ

> You've updated the copyright years for all contributors

I'm no copyright lawyer... but the files do contain code written by or code derrived from contributions from all contributors defined in the licence headers so I believe that dates are still valid.
I'm happy to make any changes if you need me to.

I have also noticed that I have not uploaded the previous version to Maven central, would you like me to do so retrospectively, and if you are happy, this version when it has been merged?

**Comment by bjorn** [comment]
I've pushed a merge that should fix the build issues on Travis CI, but the failing autotests on AppVeyor still need to be addressed. Hopefully you have an idea what's causing those?

**Comment by cdefgah** [comment]
Regarding nbactions, ipr and iml files - these files are ignored usually. 

**pom.xml** file is sufficient and enough to import the project to any modern IDE and work with it as with a Maven project.

**Comment by mikepthomas** [comment]
Sorry I havn't had much spare time lately to look at it, @cdefgah is correct, It seems to be a multiplatform issue, the development was done on Linux and it seems to not be working on Windows. The Appveyor tests that are failing all seem to be running different versions of Windows

**Comment by cdefgah** [comment]
@mikepthomas hi, Mike. I've noticed that in the tiled-java library the entire package "org.mapeditor.io.xml" is marked as deprecated. Probably there are more deprecated classes inside.

Could you, please, clarify, why this package (and other classes) are marked as deprecated, and what planned to be used instead ?

**Comment by mikepthomas** [comment]
org.mapeditor.io.xml contains classes that write out xml using custom code, I'd originally planned on replacing them with the JAXB marshaler however with the release of Java 11 javax.xml.bind has been removed from the JDK (however it is still available as a separate dependency).

**Comment by cdefgah** [comment]
@mikepthomas thank you for information, Mike

**Comment by bjorn** [comment]
> org.mapeditor.io.xml contains classes that write out xml using custom code, I'd originally planned on replacing them with the JAXB marshaler however with the release of Java 11 javax.xml.bind has been removed from the JDK (however it is still available as a separate dependency).

Indeed, I wrote that XML writer before I knew that one is (or is by now) available in the Java standard library. Rather than using the JAXB marshaler, I think it could be replaced by [`XMLStreamWriter`](https://docs.oracle.com/javase/7/docs/api/javax/xml/stream/XMLStreamWriter.html), as follows:

```java
XMLOutputFactory output = XMLOutputFactory.newInstance();
XMLStreamWriter writer = output.createXMLStreamWriter( ... );
...
```

It has pretty much the same API as the `XMLWriter` (I had originally based this writer on [the one available in libxml2](http://xmlsoft.org/html/libxml-xmlwriter.html)).

**Comment by cdefgah** [comment]
@bjorn @mikepthomas folks, I hope you don't mind if I redesign tiled-java library code. It needs heavy refactoring for sure. It will be version 2.0 and API will not be compatible with 1.xx versions.

**Comment by bjorn** [comment]
> I hope you don't mind if I redesign tiled-java library code. It needs heavy refactoring for sure. It will be version 2.0 and API will not be compatible with 1.xx versions.

I don't mind, but please try to do your refactoring incrementally in multiple pull requests, otherwise nobody may ever find the time to review the whole change.

**Comment by cdefgah** [comment]
@bjorn I would like to minimize the review time by making tests. Currently I don't fully understand the logic behind the codes. And I will ask questions later upon the work progress, to clarify the necessary points.

**Comment by bjorn** [comment]
> @bjorn is it better to ask questions here or by email ?

Here would be a good place since it's public, but let's not use this specific pull request. If you want to ask general questions before you actually open your own pull request(s), you can also use the [Tiled forum](https://discourse.mapeditor.org/).

It would be nice to first work towards merging this pull request, btw, before making further changes to the library. I believe it was only blocked by the failing autotests.

**Comment by cdefgah** [comment]
@bjorn what is the best approach in this case? Shall we wait until @mikepthomas fix PR or shall I fork this repo https://github.com/mikepthomas/tiled check what is wrong with tests, fix it and make my PR instead of Mike's ?

**Comment by bjorn** [comment]
@cdefgah You don't really need to fork the repo of @mikepthomas, you just need to add it as a remote and make a local branch based on his master branch. Then you can push that branch to your repo and open a new pull request.

**Comment by cdefgah** [comment]
@bjorn @mikepthomas I have fixed Mike's broken tests and made new PR to the bjorn's repo. Please check.

**Comment by mikepthomas** [comment]
hi @bjorn, I have just pushed another commit to support building on JDK 9+
this should fix https://github.com/bjorn/tiled/issues/2048
I have also included @cdefgah's fix from https://github.com/bjorn/tiled/pull/2030

**Comment by bjorn** [comment]
I'd like to merge this but it's still (or again, it seems) blocked by failing autotests. Does anybody know what's needed to make them pass? @mikepthomas @cdefgah?
```
[00:14:08] [ERROR] Tests run: 12, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 0.922 s <<< FAILURE! - in org.mapeditor.io.MapReaderTest
[00:14:08] [ERROR] testReadingExampleOutsideMap(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.468 s  <<< ERROR!
[00:14:08] javax.imageio.IIOException: Can't read input file!
[00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingExampleOutsideMap(MapReaderTest.java:181)
[00:14:08] 
[00:14:08] [ERROR] testReadingCsvMapEmbeddedImageCollection(org.mapeditor.io.MapReaderTest)  Time elapsed: 0 s  <<< ERROR!
[00:14:08] javax.imageio.IIOException: Can't get input stream from URL!
[00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingCsvMapEmbeddedImageCollection(MapReaderTest.java:125)
[00:14:08] Caused by: java.io.FileNotFoundException: C:\projects\tiled\util\java\libtiled-java\csvmap_embedded_image_collection_1.png (The system cannot find the file specified)
[00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingCsvMapEmbeddedImageCollection(MapReaderTest.java:125)
[00:14:08] 
[00:14:08] [ERROR] testReadingDesertMap(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.016 s  <<< ERROR!
[00:14:08] java.io.FileNotFoundException: C:\projects\tiled\util\java\libtiled-java\desert.tsx (The system cannot find the file specified)
[00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingDesertMap(MapReaderTest.java:149)
[00:14:08] 
[00:14:08] [ERROR] testReadingCsvMap(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.125 s  <<< ERROR!
[00:14:08] javax.imageio.IIOException: Can't read input file!
[00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingCsvMap(MapReaderTest.java:105)
[00:14:08] 
[00:14:08] [ERROR] testReadingSewersMap(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.031 s  <<< ERROR!
[00:14:08] javax.imageio.IIOException: Can't read input file!
[00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingSewersMap(MapReaderTest.java:73)
[00:14:08] 
[00:14:08] [ERROR] testReadingPerspectiveWallsMap(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.078 s  <<< ERROR!
[00:14:08] java.io.FileNotFoundException: C:\projects\tiled\util\java\libtiled-java\perspective_walls.tsx (The system cannot find the file specified)
[00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingPerspectiveWallsMap(MapReaderTest.java:201)
[00:14:08] 
[00:14:08] [ERROR] testReadingFlippedTiles(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.063 s  <<< ERROR!
[00:14:08] java.io.FileNotFoundException: C:\projects\tiled\util\java\libtiled-java\..\desert\desert.tsx (The system cannot find the path specified)
[00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingFlippedTiles(MapReaderTest.java:260)
[00:14:08] 
[00:14:08] [ERROR] testReadingHexagonalMap(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.063 s  <<< ERROR!
[00:14:08] javax.imageio.IIOException: Can't read input file!
[00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingHexagonalMap(MapReaderTest.java:221)
[00:14:08] 
[00:14:08] [INFO] 
[00:14:08] [INFO] Results:
[00:14:08] [INFO] 
[00:14:08] [ERROR] Errors: 
[00:14:08] [ERROR]   MapReaderTest.testReadingCsvMap:105 � IIO Can't read input file!
[00:14:08] [ERROR]   MapReaderTest.testReadingCsvMapEmbeddedImageCollection:125 � IIO Can't get inp...
[00:14:08] [ERROR]   MapReaderTest.testReadingDesertMap:149 � FileNotFound C:\projects\tiled\util\j...
[00:14:08] [ERROR]   MapReaderTest.testReadingExampleOutsideMap:181 � IIO Can't read input file!
[00:14:08] [ERROR]   MapReaderTest.testReadingFlippedTiles:260 � FileNotFound C:\projects\tiled\uti...
[00:14:08] [ERROR]   MapReaderTest.testReadingHexagonalMap:221 � IIO Can't read input file!
[00:14:08] [ERROR]   MapReaderTest.testReadingPerspectiveWallsMap:201 � FileNotFound C:\projects\ti...
[00:14:08] [ERROR]   MapReaderTest.testReadingSewersMap:73 � IIO Can't read input file!
```
The paths of the files it fails to load seem to be missing the `src/test/resources/...` part.

**Comment by cdefgah** [comment]
If I recall correctly there was a problem with composing file/folder path, approach was platform dependent and was related to the folder file separator symbol.
 
I did not understand fully the algorithm of @mikepthomas 's implementation so I did not change it.

Probably  @mikepthomas could answer this question.

**Comment by thinkwithlinc** [comment]
> I'd like to merge this but it's still (or again, it seems) blocked by failing autotests. Does anybody know what's needed to make them pass? @mikepthomas @cdefgah?
> 
> ```
> [00:14:08] [ERROR] Tests run: 12, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 0.922 s <<< FAILURE! - in org.mapeditor.io.MapReaderTest
> [00:14:08] [ERROR] testReadingExampleOutsideMap(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.468 s  <<< ERROR!
> [00:14:08] javax.imageio.IIOException: Can't read input file!
> [00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingExampleOutsideMap(MapReaderTest.java:181)
> [00:14:08] 
> [00:14:08] [ERROR] testReadingCsvMapEmbeddedImageCollection(org.mapeditor.io.MapReaderTest)  Time elapsed: 0 s  <<< ERROR!
> [00:14:08] javax.imageio.IIOException: Can't get input stream from URL!
> [00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingCsvMapEmbeddedImageCollection(MapReaderTest.java:125)
> [00:14:08] Caused by: java.io.FileNotFoundException: C:\projects\tiled\util\java\libtiled-java\csvmap_embedded_image_collection_1.png (The system cannot find the file specified)
> [00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingCsvMapEmbeddedImageCollection(MapReaderTest.java:125)
> [00:14:08] 
> [00:14:08] [ERROR] testReadingDesertMap(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.016 s  <<< ERROR!
> [00:14:08] java.io.FileNotFoundException: C:\projects\tiled\util\java\libtiled-java\desert.tsx (The system cannot find the file specified)
> [00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingDesertMap(MapReaderTest.java:149)
> [00:14:08] 
> [00:14:08] [ERROR] testReadingCsvMap(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.125 s  <<< ERROR!
> [00:14:08] javax.imageio.IIOException: Can't read input file!
> [00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingCsvMap(MapReaderTest.java:105)
> [00:14:08] 
> [00:14:08] [ERROR] testReadingSewersMap(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.031 s  <<< ERROR!
> [00:14:08] javax.imageio.IIOException: Can't read input file!
> [00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingSewersMap(MapReaderTest.java:73)
> [00:14:08] 
> [00:14:08] [ERROR] testReadingPerspectiveWallsMap(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.078 s  <<< ERROR!
> [00:14:08] java.io.FileNotFoundException: C:\projects\tiled\util\java\libtiled-java\perspective_walls.tsx (The system cannot find the file specified)
> [00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingPerspectiveWallsMap(MapReaderTest.java:201)
> [00:14:08] 
> [00:14:08] [ERROR] testReadingFlippedTiles(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.063 s  <<< ERROR!
> [00:14:08] java.io.FileNotFoundException: C:\projects\tiled\util\java\libtiled-java\..\desert\desert.tsx (The system cannot find the path specified)
> [00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingFlippedTiles(MapReaderTest.java:260)
> [00:14:08] 
> [00:14:08] [ERROR] testReadingHexagonalMap(org.mapeditor.io.MapReaderTest)  Time elapsed: 0.063 s  <<< ERROR!
> [00:14:08] javax.imageio.IIOException: Can't read input file!
> [00:14:08] 	at org.mapeditor.io.MapReaderTest.testReadingHexagonalMap(MapReaderTest.java:221)
> [00:14:08] 
> [00:14:08] [INFO] 
> [00:14:08] [INFO] Results:
> [00:14:08] [INFO] 
> [00:14:08] [ERROR] Errors: 
> [00:14:08] [ERROR]   MapReaderTest.testReadingCsvMap:105 � IIO Can't read input file!
> [00:14:08] [ERROR]   MapReaderTest.testReadingCsvMapEmbeddedImageCollection:125 � IIO Can't get inp...
> [00:14:08] [ERROR]   MapReaderTest.testReadingDesertMap:149 � FileNotFound C:\projects\tiled\util\j...
> [00:14:08] [ERROR]   MapReaderTest.testReadingExampleOutsideMap:181 � IIO Can't read input file!
> [00:14:08] [ERROR]   MapReaderTest.testReadingFlippedTiles:260 � FileNotFound C:\projects\tiled\uti...
> [00:14:08] [ERROR]   MapReaderTest.testReadingHexagonalMap:221 � IIO Can't read input file!
> [00:14:08] [ERROR]   MapReaderTest.testReadingPerspectiveWallsMap:201 � FileNotFound C:\projects\ti...
> [00:14:08] [ERROR]   MapReaderTest.testReadingSewersMap:73 � IIO Can't read input file!
> ```
> 
> The paths of the files it fails to load seem to be missing the `src/test/resources/...` part.

I know what caused thi
MapReader#readMap is diffent with TMXMapReader#readMap
MapReader lack of windows|unix path translator

https://github.com/bjorn/tiled/commit/f0b24c447b009e9b587ad599dd9a4578d17fb24f

**Comment by bjorn** [comment]
> I know what caused this
> MapReader#readMap is diffent with TMXMapReader#readMap
> MapReader lack of windows|unix path translator
> 
> see this commit
> [f0b24c4](https://github.com/bjorn/tiled/commit/f0b24c447b009e9b587ad599dd9a4578d17fb24f)

Ah, that explains, so it's likely the result of merging this old PR with that more recent change that is breaking the tests. We should probably undo [this part](https://github.com/bjorn/tiled/pull/1925/files#diff-b9b39b617c1cc15a575c5b5ef1483291R803-R807) of this change.

**Comment by thinkwithlinc** [comment]
> > I know what caused this
> > MapReader#readMap is diffent with TMXMapReader#readMap
> > MapReader lack of windows|unix path translator
> > see this commit
> > [f0b24c4](https://github.com/bjorn/tiled/commit/f0b24c447b009e9b587ad599dd9a4578d17fb24f)
> 
> Ah, that explains, so it's likely the result of merging this old PR with that more recent change that is breaking the tests. We should probably undo this part of the change:
> 
> https://github.com/bjorn/tiled/blob/67bdf80046abf0b04e3b03ecef53df4d053bfdc6/util/java/libtiled-java/src/main/java/org/mapeditor/io/TMXMapReader.java#L803-L807

MapReader  last commit was 2017/07/04 ,maybe it can replace by TMXMapReader and mark as Deprecated

**Comment by bjorn** [comment]
> MapReader last commit was 2017/07/04 ,maybe it can replace by TMXMapReader and mark as Deprecated

Hmm, I never realized we had two map readers now. The `MapReader` class was added by @mikepthomas. Maybe he can tell us whether it was meant to replace `TMXMapReader` eventually, or what the difference between these two classes is.

**Comment by bjorn** [comment]
If my above change fixes the autotests on Windows, then I think the remaining thing to do before this PR can be merged is to remove all those hidden IDE settings files.

**Comment by bjorn** [comment]
Actually, those `.project`, `.classpath` and `.settings` files are quite small and some people write they [do include them in version control](https://stackoverflow.com/questions/2818239/classpath-and-project-check-into-version-control-or-not/2819639) (maybe not `.settings/*.prefs`, but we can just delete that again if it causes problems).

Many thanks @mikepthomas for these updates and sorry not merging this sooner!

**Comment by cdefgah** [comment]
@bjorn .project .classpath .settings - are Eclipse-related project files. If a project contains well-formed *.pom file it is enough to open this project and work with it in any modern java IDE as a maven project. Also it can be opened in Eclipse.

Probably, in some cases, when project team works only in eclipse, it makes sense to include these files to repository. But in case of an open source project the picture is a bit different.

IMO we should not include IDE specific project files to the repository unless it is strictly necessary.

In this particular case it is not necessary.

**Comment by bjorn** [comment]
@cdefgah Alright, makes sense! But I think it would be good to verify that our pom files are indeed working out of the box before we delete those files (or did you do it already?). I personally don't have any Java IDE installed.

**Comment by cdefgah** [comment]
I use Intellij IDEA for java development and I've loaded this project as a [Maven project](https://maven.apache.org/) and worked with it. I think the pom.xml file is correct.

**Comment by bjorn** [comment]
@cdefgah Alright, would you have time to redo #2030, regarding just the removal of the project files?

@mikepthomas Could you push a new version of libtiled to Maven Central?

**Comment by cdefgah** [comment]
@bjorn ok, will do it soon

**Comment by cdefgah** [comment]
@bjorn PR created: https://github.com/bjorn/tiled/pull/2752

**Comment by mikepthomas** [comment]
> @mikepthomas Could you push a new version of libtiled to Maven Central?

I have just pushed a release, with the version number 1.2.3:
https://oss.sonatype.org/#nexus-search;gav~org.mapeditor~libtiled~1.2.3~~

It should shortly be synced to central 👍

**Pull request merged**
