### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by kokeszko**
Initial commit of polish translation.
Known issues:
- some fields left unchanged
- possible problems with shortcuts in application (translation with & sign)

Definitely it requires verification.

### CODE REVIEW

**Comment by bjorn** [comment]
First of all, thanks for working on adding a Polish translation!

> some fields left unchanged

There seem to be really few. Were you just not sure how to translate them? Just ask if you're unsure what something means.

> possible problems with shortcuts in application (translation with & sign)

The shortcuts created by &-sign can change based on the language. Generally it makes sense to take the first letter of the main action word, but you should avoid using the same accelerator multiple times in a menu.

**Comment by bjorn** [comment]
Seems like the translation file is too big for inline commenting on GitHub. I noticed one problematic translation, which is that the "L" shortcut of the "CreatePolylineObjectTool" is translated as ":". I think you should just keep this on "L".

**Comment by kokeszko** [comment]
True, not much fields left. Only those i couldn't find a proper word in Polish language and some obvious like "untitled.tmx". Still I keep in mind that i could make some mistakes and this translation should be verified once again.

I've been trying to pick first letters as a shortcut but during translation I found out that there is a lot of words starting with the same letter. I've tried to do my best to keep those shortcuts as unique as possible, still it needs to be verified.

Colon as a shortcut was a mistake. I've already changed it and i'll push it again.

**Comment by bjorn** [comment]
I've so far been unsuccessful either on IRC or on Twitter to find another Polish person willing to review the translation. Maybe you can help find another Polish Tiled user?

**Comment by kokeszko** [comment]
I don't know anyone willing to review polish translation. If no one occurs I'll close this pull request.

**Comment by bjorn** [comment]
> If no one occurs I'll close this pull request.

For sure you're not the only Polish Tiled user! There is no need to close this, we can just give it some time and in the meantime you could ponder about the still missing entries. :-)

**Comment by kokeszko** [comment]
Sure, I've also noticed some mistakes and I'll try to fix it.
Still trying to find propper words for "staggered maps".

**Comment by Okurwieniec** [comment]
I just finished checking translations and i found some things that perhaps needs to be corrected.
Here they go:

line 100
        <source>Export the specified tmx file to target</source>
        <translation>Eksportuj określony plik tmx do celu</translation>

i propose wskazany instead of określony

line 1390
        <source>v0.9 and later</source>
        <translation>v0.8 i późniejsze</translation>

v0.9 not 0.8

line 2164
 <translation>Nie powiodło się otwarcie mapy regół:

reguł not regół

line 2336
        <source>The command crashed.</source>
        <translation>Polecenie wywaliło się.</translation>

perhaps better would be: Polecenie nie zadziałało

line 2548
        <source>Could not allocate sufficient memory for the image. Try reducing the zoom level or using a 64-bit version of Tiled.</source>
        <translation>Nie można przydzielić wystarczającą ilość pamięci dla obrazka. Spróbuj zmniejszyć poziom powiększenia lub korzystaj z wersji 64-bitowej Tiled.</translation>

should be: wystarczającej ilości

line 2558
        <source>The resulting image would be %1 x %2 pixels and take %3 GB of memory. Tiled is unable to create such an image. Try reducing the zoom level.</source>
        <translation>Uzyskany obrazek byłby%1 x%2 pikseli i bierze%3 GB pamięci. Tiled nie jest w stanie stworzyć takiego obrazka. Spróbuj zmniejszyć poziom powiększenia.</translation>

instead of bierze i propose: zajmowałby

line 2779
        <source>Exported to %1</source>
        <translation>Eksportuj do %1</translation>

i propose Wyeksportowano instead of Exportuj

line 2818
 <translation>Niektóre pliki eksportu istnieje:</translation>

istnieją

line 3174
        <source>Change Object Type</source>
        <translation>Zmień Nazwę Typu</translation>

Zmień Typ Obiektu

in menu in widok/widoki i paski narzędzi/ i can see Tile Stamps in english

Thats all i could see.

**Comment by kokeszko** [comment]
I agree with all comments. I'll commit again.
@Okurwieniec  any suggestions for "Tile stamps"?

**Comment by Okurwieniec** [comment]
Not really. I'm afraid all my life i used english editors and i really have no idea how it could be named in polish. If i have some idea ill post that here :) This stamp tool seem similar to one in photoshop, so first ill check how it was named.

**Comment by kokeszko** [comment]
@Okurwieniec in PS it's called "Stempel". So I'm wondering if i should rename already set translation.
line 3863: "Tile Stamps" can be translated to "Stemple Kafelka"

Already set translations:
line 3744: "Stamp Brush" to "Pędzel Stempla"
line 3835: "Stamp" to "Stempel"
line 3848: "Delete Stamp" to "Usuń Stempel"
line 3858: "Choose the Stamps Folder" to "Wybierz Katalog Stempli"
line 3868: "Add New Stamp" to "Dodaj Nowy Stempel"
line 3878: "Duplicate Stamp" to "Duplikuj Stempel"
line 3888: "Set Stamps Folder" to "Ustaw Katalog Stempli"

**Comment by Okurwieniec** [comment]
@kokeszko  yes it looks good. I tryed to call my friend in Poland so he tells me but you found out faster.

**Comment by bjorn** [comment]
Thanks a lot for the review @Okurwieniec!

Do both of you now consider this translation ready for merging?

**Comment by kokeszko** [comment]
Still it lacks few translations but definitely it is ready for merging.

**Comment by bjorn** [comment]
Awesome, thanks! Since it would be good to include this translation with a possible Tiled 0.14.2 release, I've pushed the translation to the `0.14` branch with commit 9b7bce7ac3d81403061f4aa7660a6c31865241ff. It's also merged down to `master` so that it will be included in the daily builds.

**Pull request closed without merging**
