### PR TITLE
Automapper warnings are now logged in the console

### PR DESCRIPTION
**Pull request by Phlosioneer**
I was unable to test this commit, because I couldn't come up with a
test case.

### CODE REVIEW

**Comment by bjorn** [comment]
Hmm, the AutoMapping warnings and errors should already be showing in both the Console and Issues views since https://github.com/bjorn/tiled/commit/9f92741039b521add6eae14a32c9543525360ce7#diff-9c5d1f9307da46d8b94990bb8eb6ca79 (and extended with callbacks in https://github.com/bjorn/tiled/commit/31496597b76a21bb70634be8fe70991521fb70df#diff-9c5d1f9307da46d8b94990bb8eb6ca79).

This change would probably cause those to be duplicated. Why did you make it?

**Comment by Phlosioneer** [comment]
I’m going through old issues and trying to solve them to better understand the codebase before I start doing my own fork. This PR is for #954, marked good first issue. The error message seemed to be discarded. However, as I said in the PR, I wasn’t able to come up with a test case.

**Comment by bjorn** [comment]
@Phlosioneer Ah, that's great, though I'm sad to hear you're planning to start a fork. Why is that?

**Comment by Phlosioneer** [comment]
I just mean a fork for my own game dev. Specifically, I need a constraint based layout engine (for making ui’s that use tile sets), more complex object scripting, object grouping, locking individual objects (an issue exists for it already and I’m working on it), better support for scripts modifying the tmx structure as it’s saved/loaded (working on it), support for generated images (opened an issue), and support for nested maps (my metatile PR is a major step toward this). 

I’m going to be opening PR’s for each of these things to upstream as much as possible, but there’s things in there that you’re probably not interested in supporting. Or, I’ll make design decisions you might disagree with, for maintenance/future expansion reasons. So that’s why I’m expecting to need a local fork.

**Comment by bjorn** [comment]
@Phlosioneer Ah, alright. I really appreciate your effort to upstream as much as possible, and I'll be sure to help as much as I can with that.

**Pull request closed without merging**
