### PR TITLE
enable setting views through tiled

### PR DESCRIPTION
**Pull request by willt**
This should allow views in gm rooms to be configured through tiled. They syntax is a little long but there isn't really a better way to do it that I can think of short of having a custom drop down.

### CODE REVIEW

**Comment by bjorn** [comment]
> They syntax is a little long but there isn't really a better way to do it that I can think of short of having a custom drop down.

Actually, wouldn't it be nicer to support rectangular objects of with type "View"? That way, at least the x, y, width and height can be visually edited, and only all the other properties would need to be done as custom properties. And they would no longer need to be numbered.

Also, would it be possible to set `enableViews` based on whether any views have been configured? Or would there be a reason to enable this without views, or to disable it even though you defined views?

**Comment by willt** [comment]
Yes rectangular objects to represent views would be nice. It would make
defining the extra properties much cleaner too. I was trying to work with
whats there. I know once I setup a view I really never change it.

Yes you could set enableViews based on if any views were configured. I
don't think there is ever a reason to disable it if you are using views. If
you don't want it enabled then don't define views.

**Comment by bjorn** [comment]
> Yes rectangular objects to represent views would be nice. It would make
> defining the extra properties much cleaner too. I was trying to work with
> whats there. I know once I setup a view I really never change it.

Are you interested in adjusting your patch to work with rectangle objects?

**Comment by bjorn** [comment]
Superseded by #1621.

**Pull request closed without merging**
