### PR TITLE
TMXMapReader can load maps from resources using readMapFromResources

### PR DESCRIPTION
**Pull request by mschroeder-github**
Added that TMXMapReader can read maps from resources instead of only files.

### CODE REVIEW

**Comment by bjorn** [comment]
From the tests we can see that it is possible to create a `URL` that points to a resource:

https://github.com/bjorn/tiled/blob/233ff4e1e7324b8d7de3f59d2238d1d92a8cd1e1/util/java/libtiled-java/src/test/java/org/mapeditor/io/MapReaderTest.java#L290-L293

Do you think it would be possible to adjust the API to use `URL` instead of `String`, so that the `boolean fromResources` can be avoided?

**Comment by mschroeder-github** [comment]
I also saw it and I tried to do it this way. Somehow my tests failed. But you are right, I tested it again and it could work (also for built fat jar). My test code:
```java
public class Main {
    public static void main(String[] args) throws IOException {
        ClassLoader classLoader = Main.class.getClassLoader(); 
        URL url = classLoader.getResource("path/to/test.txt"); //do not use starting '/' here
        System.out.println(url);
        System.out.println(url.openStream());
    }
}
```
It works when started in IDE:
```
file:/(...)/target/classes/path/to/test.txt
java.io.BufferedInputStream@6d06d69c
```
And it works when using `java -jar fat.jar`:
```
jar:file:/(...)/target/fat.jar!/path/to/test.txt
sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@6bc7c054
```

This means my implementation could be done easier. Directly pass the `URL` with `Map readMap(URL url)` as you suggest. 

I could make another pull request.

**Comment by bjorn** [comment]
> I could make another pull request.

I think you can just continue the work in this pull request?

**Comment by bjorn** [comment]
Superseded by #2829.

**Pull request closed without merging**
