### PR TITLE
Added wangtiles docs

### PR DESCRIPTION
**Pull request by Bdtrotte**

### CODE REVIEW

**Comment by stoneymcpot86** [comment]
a
Sent from my Sony Xperia™ smartphone


---- Benjamin Trotter wrote ----

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/bjorn/tiled/pull/1702

Commit Summary

  *   Added wangtiles docs

File Changes

  *   M docs/index.rst<https://github.com/bjorn/tiled/pull/1702/files#diff-0> (1)
  *   M docs/manual/editing-tile-layers.rst<https://github.com/bjorn/tiled/pull/1702/files#diff-1> (22)
  *   A docs/manual/images/wangtiles/01-wangbutton.jpg<https://github.com/bjorn/tiled/pull/1702/files#diff-2> (0)
  *   A docs/manual/images/wangtiles/02-wangsetview.jpg<https://github.com/bjorn/tiled/pull/1702/files#diff-3> (0)
  *   A docs/manual/images/wangtiles/03-wangsetproperties.jpg<https://github.com/bjorn/tiled/pull/1702/files#diff-4> (0)
  *   A docs/manual/images/wangtiles/04-patternview.jpg<https://github.com/bjorn/tiled/pull/1702/files#diff-5> (0)
  *   A docs/manual/images/wangtiles/05-assigningpattern.jpg<https://github.com/bjorn/tiled/pull/1702/files#diff-6> (0)
  *   A docs/manual/images/wangtiles/06-assigningedge.jpg<https://github.com/bjorn/tiled/pull/1702/files#diff-7> (0)
  *   A docs/manual/images/wangtiles/07-fullassignment.jpg<https://github.com/bjorn/tiled/pull/1702/files#diff-8> (0)
  *   A docs/manual/images/wangtiles/08-stampbrush.jpg<https://github.com/bjorn/tiled/pull/1702/files#diff-9> (0)
  *   A docs/manual/images/wangtiles/09-bucketfill.jpg<https://github.com/bjorn/tiled/pull/1702/files#diff-10> (0)
  *   A docs/manual/images/wangtiles/10-wangbrush.jpg<https://github.com/bjorn/tiled/pull/1702/files#diff-11> (0)
  *   A docs/manual/using-wang-tiles.rst<https://github.com/bjorn/tiled/pull/1702/files#diff-12> (96)

Patch Links:

  *   https://github.com/bjorn/tiled/pull/1702.patch
  *   https://github.com/bjorn/tiled/pull/1702.diff

**Comment by bjorn** [comment]
I've made some minor adjustments.

I'm missing a few things still:

* An important difference between the terrain system and the Wang tiles is that the former only works with _corners_ whereas the latter can also work with _edges_. This should make Wang tiles useful for drawing paths and fences, which is a use-case that the terrain tool does not cover.

* I think the documentation does not cover sufficiently the non-random way of using Wang tiles. Maybe the "Editing With Wang Methods" section could have an explicit sub-section for the Wang mode and the Wang Brush.

* The Wang Brush section on the tile layer page should link to the Wang tiles page.

* You didn't mention that you can customize the color, name and image, to make the Wang colors more recognizable.

* I think it would make sense to covering certain common Wang tile patterns (like the ones supported by GameMaker Studio 2: [2-corner](http://www.cr31.co.uk/stagecast/wang/2corn.html) and the [blob tileset](http://www.cr31.co.uk/stagecast/wang/blob.html)).

**Comment by bjorn** [comment]
(rebased on latest master because of conflicts)

**Comment by bjorn** [comment]
(rebased again because I accidentally included a patch for the 1.0 branch in previous rebase)

**Pull request merged**
