### PR TITLE
Let travis build with g++ 4.8

### PR DESCRIPTION
**Pull request by Ablu**
lets see if this works

### CODE REVIEW

**Comment by Ablu** [comment]
Giving up for now. Running out of time. Need to look at it later again.

**Comment by bjorn** [comment]
Thanks for trying, @Ablu!

**Comment by bjorn** [comment]
What about, instead of trying to tell qmake to use different compiler executable names, you'd tell Ubuntu to change the gcc symlink to the newer version? I think there's some update-alternatives thingy for this.

**Comment by Ablu** [comment]
Ok this should succeed now once `-std=c++11x` is specified for qt4 builds (qt4's qmake does not support `CONFIG += c++11`

**Comment by bjorn** [comment]
Yeah, i can fix that, but I hope you can still need to make it not break the clang build. :-)

**Comment by Ablu** [comment]
Fixed :)

**Comment by bjorn** [comment]
Awesome! :-)

**Pull request merged**
