### PR TITLE
UPDATE - Brazilian Portuguese language

### PR DESCRIPTION
**Pull request by laetemn**
- Corrections.
- Review.

### CODE REVIEW

**Comment by bjorn** [comment]
Many thanks! I've [tweeted](https://twitter.com/thorbjorn81/status/651503949510541312) about this to ask for somebody who could review this update.

**Comment by arthurferrai** [comment]
I have some suggestions. Should I annotate them over here?

**Comment by bjorn** [comment]
@arthurferrai Normally you'd comment inline on the pull request under the "Files changed" tab, but the number of changes in this file are unfortunately too much for GitHub. So you can see all the actual changes here:

https://github.com/laetemn/tiled-pt_BR/commit/83918bf702cc80b930fadc7adcdf8b414fb2cb37.patch

Suggestions for improvements should probably just be quoted here in a comment (you can quote some translation by putting a `>` character at the start of the line). Of course, suggestions for improvement for existing translations are welcome too.

Thanks for reviewing!

**Comment by arthurferrai** [comment]
Ok, here are some suggestions (since I don't know exactly how to reference them, I pasted some context before the suggestions so a simple 'Ctrl-F' should find the part):
```
     <message>
         <location line="+5"/>
         <source>Disable hardware accelerated rendering</source>
-        <translation type="unfinished"></translation>
+        <translation>Desativar hardware de renderização acelerada</translation>
     </message>
```
I would translate this to `Desativar renderização acelerada por hardware`.

```
     <message>
         <location line="+10"/>
         <source>Settings</source>
-        <translation type="unfinished">Preferências</translation>
+        <translation>Preferências</translation>
     </message>
```
`Settings` should translate to `Configurações`.

```
     <message>
         <location line="+6"/>
         <source>Only include &amp;visible layers</source>
-        <translation type="unfinished">Apenas incluir &amp;camadas visíveis</translation>
+        <translation>Incluir somente &amp;camadas visíveis</translation>
     </message>
```
Here, I suggest just to change `&amp;` position to match the same shortcut as english version (IIRC they are used as shortcut letter on Windows' menus): `Incluir somente camadas &amp;visíveis`

```
     <message>
         <location line="+70"/>
         <source>This seems to be no valid flare map. A Flare map consists of at least a header section, a tileset section and one tile layer.</source>
-        <translation>Este não parece ser um mapa de Flare válido. Um mapa de Flare consiste de pelo menos uma seçao de cabeçalho, uma seçao de tileset e uma camada.</translation>
+        <translation>Este não parece ser um mapa do Flare válido. Um mapa do Flare consiste de pelo menos uma seçao de cabeçalho, uma seçao de tileset e uma camada.</translation>
     </message>
```
Here, there are missing tildes on `seçao` (should be `seção`).

```
     <message>
         <location filename="../src/automappingconverter/converterwindow.ui" line="+14"/>
         <source>Tiled Automapping Rule Files Converter</source>
-        <translation>Conversor de Arquivos de Regras de Automapeamento de Tiles</translation>
+        <translation>Converter Arquivos de Regras de Automapeamento de Tiles</translation>
     </message>
```
Since it's a tool, I'd stick with `Conversor` (a noun) instead of `Converter` (a verb).

```
         <location filename="../src/libtiled/varianttomapconverter.cpp" line="-184"/>
         <source>Tileset tile index negative:
 &apos;%1&apos;</source>
-        <translation type="unfinished"></translation>
+        <translation>Índice do tiliset para o tile negativo:
+%1</translation>
     </message>
```
`tiliset` should be `tileset`.

```
     <message>
         <location line="+16"/>
         <source>Object line width:</source>
-        <translation type="unfinished"></translation>
+        <translation>Largura da linah do objeto:</translation>
     </message>
```
There's a typo in `linah` (should be `linha`).

```
     <message>
         <location line="+17"/>
         <source>Remove Selected Object Types</source>
-        <translation>Remover os tipos de objeto selecionados</translation>
+        <translation>Remover o(s) tipo(s) de objet(o) selecionado(s)</translation>
     </message>
```
`objet(o)` should be `objeto(s)`.

```
     <message>
         <location line="-164"/>
         <source>Reloading Python scripts</source>
-        <translation type="unfinished"></translation>
+        <translation>Recarregando  scripts Python</translation>
     </message>
```
There are 2 spaces in `Recarregando  scripts`.

```
     <message>
         <location line="+2"/>
         <source>Size Slash</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>
     </message>
```
I think this should be `Tamanho da Barra`.

```
     <message>
         <location line="+246"/>
         <source>T-Engine4 map files (*.lua)</source>
-        <translation>Arquivos do tipo T-Engine4 (*.lua)</translation>
+        <translation>Arquivos dde mapa do T-Engine4 (*.lua)</translation>
     </message>
```
`dde` should be `de`.

```
     <message>
         <location line="+99"/>
         <location filename="../src/tiled/tileanimationeditor.cpp" line="+507"/>
         <source>Preview</source>
-        <translation type="unfinished"></translation>
+        <translation></translation>
     </message>
```
`Preview` can be translated to `Pré-visualizar` ou `Prévia`.

```
     <message>
         <location line="+46"/>
         <source>Out of Memory</source>
-        <translation type="unfinished"></translation>
+        <translation>Fora da Memória</translation>
     </message>
```
If this indicates there's no memory available, this should be `Falta de memória` ou `Memória insuficiente`.

```
     <message>
         <location line="+37"/>
         <source>Exported to %1</source>
-        <translation type="unfinished"></translation>
+        <translation>Exportar para %1</translation>
     </message>
```
If it indicates that it's already exported, should be `Exportado para %1`.

```
     <message>
         <location line="+10"/>
         <source>Tileset Changes</source>
-        <translation>Mudanças no Tileset</translation>
+        <translation>Alterar Tileset</translation>
     </message>
```
I'd stick with first one here.

```
&lt;p&gt;Your support as a patron makes a big difference to me as the main developer and maintainer of Tiled. It allows me to spend less time working for money elsewhere and spend more time working on Tiled instead.&lt;/p&gt;
 &lt;p&gt;Keep an eye out for exclusive updates in the Activity feed on my Patreon page to find out what I&apos;ve been up to in the time I could spend on Tiled thanks to your support!&lt;/p&gt;
 &lt;p&gt;&lt;i&gt;Thorbj&amp;oslash;rn Lindeijer&lt;/i&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
-        <translation type="unfinished"></translation>
+        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;
+&lt;h3&gt;Obrigado pela ajuda!&lt;/h3&gt;
+&lt;p&gt;Seu apoio como patrono faz uma grande diferença para mim como o principal desenvolvedor e mantenedor do Tiled. Ele me permite gastar menos tempo de trabalho para arrumar dinheiro em outro lugar e passar mais tempo trabalhando no Tiled.&lt;/p&gt;
+&lt;p&gt;Mantenha-se informado sobre as atualizações exclusivas no feed de Atividade na minha página Patreon para descobrir o que eu estive fazendo até mesmo no tempo que eu poderia gastar em agradecimentos por seu apoio ao Tiled!&lt;/p&gt;
+&lt;p&gt;&lt;i&gt;Thorbj&amp;oslash;rn Lindeijer&lt;/i&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
     </message>
```
I'd write the final part as this:
```
Mantenha-se informado sobre as atualizações exclusivas no feed de Atividade na minha página Patreon para descobrir o que eu estive fazendo no tempo que eu posso usar no Tiled graças ao seu suporte!
```

```
     <message>
         <location line="+2"/>
@@ -3362,12 +3373,16 @@ Por favor selecione o formato específico.</translation>
 &lt;p&gt;Please consider supporting me as a patron. Your support would make a big difference to me, the main developer and maintainer of Tiled. I could spend less time working for money elsewhere and spend more time working on Tiled instead.&lt;/p&gt;
 &lt;p&gt;Every little bit helps. Tiled has a lot of users and if each would contribute a small donation each month I will have time to make sure Tiled keeps getting better.&lt;/p&gt;
 &lt;p&gt;&lt;i&gt;Thorbj&amp;oslash;rn Lindeijer&lt;/i&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
-        <translation type="unfinished"></translation>
+        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;
+&lt;h3&gt;Com a sua ajuda eu posso continuar a melhorar o Tiled!&lt;/h3&gt;
+&lt;p&gt;Por favor, considere me apoiar como patrono. Seu apoio seria uma grande diferença para mim, o principal desenvolvedor e mantenedor do Tiled. Eu poderia gastar menos tempo de trabalho para arrumar dinheiro em outro lugar e passar mais tempo trabalhando no Tiled.&lt;/p&gt;
+&lt;p&gt;Cada pequena ajuda. Tiled possui um monte de usuários e se cada um contribuir com uma pequena doação cada mês eu vou ter tempo para me certificar de que o Tiled será cada vez melhor.&lt;/p&gt;
+&lt;p&gt;&lt;i&gt;Thorbj&amp;oslash;rn Lindeijer&lt;/i&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
     </message>
```
Where it has `Cada pequena ajuda.` should be `Cada centavo conta.` or `Toda ajuda é bem-vinda`.

```
     <message>
         <location line="-420"/>
         <source>Odd</source>
-        <translation type="unfinished"></translation>
+        <translation>Ímpar</translation>
     </message>
     <message>
         <location line="+1"/>
         <source>Even</source>
-        <translation type="unfinished"></translation>
+        <translation>Até</translation>
     </message>
```
If `Odd` translates to `Ímpar` (in case of a number not being divisible by 2), `Even` should be translated to `Par`.

Other than that, I think the translation is pretty good.

**Comment by laetemn** [comment]
@arthurferrai You speak Portuguese?
We could try to discuss improvements in the translation to the Brazilian Portuguese language.

==========================================================================

Você fala português?
Poderíamos tratar de discutir melhorias na tradução para o idioma Português Brasileiro.

**Comment by arthurferrai** [comment]
@laetemn Sure, would be great! How should we do this?

Claro, seria ótimo! Como poderíamos fazer isso?

**Comment by laetemn** [comment]
Fork Tiled: https://github.com/laetemn/tiled-pt_BR/pulls
E-mail: laetemn@gmail.com
Tel.: +55 11 952871593 (Whatsapp) Brazil

Tenho essas três meios de contato para discutirmos melhorias na tradução.

**Comment by arthurferrai** [comment]
Me manda um email, acho mais prático :D
arthur.ferrai@gmail.com

**Comment by laetemn** [comment]
@arthurferrai Já mandei um email! :D

**Comment by bjorn** [comment]
Alright, many thanks @laetemn for the huge update and thanks to @arthurferrai for the review and further improvements! I've pushed this translation to the `0.14` branch now in commit c0314cfb93a12f04c2be9c75abf94c49202a7a1c.

**Comment by laetemn** [comment]
:+1: 

PERFECT!
I am awaiting the release of 'Tile 1.0' to start translating.

**Pull request closed without merging**
