### PR TITLE
TR language support & TR translations

### PR DESCRIPTION
**Pull request by nuriu**
I will continue to translation if this could merge.

### CODE REVIEW

**Comment by bjorn** [comment]
Looks like a great start, thanks! If you have any questions about any strings, just ask.

I could merge it now, but don't you want to finish it first? Also, I would merge this to the 0.15 branch so that it can be included with Tiled 0.15.2.

**Comment by nuriu** [comment]
I will continue then. It would be great i think. Do next release have any deadlines?

**Comment by bjorn** [comment]
For new feature releases, I announce a string freeze about two weeks before I want to make the release, so that all translations can be updated. Patch releases don't have a deadline. They are just made when there were some important bugfixes, but also for translation updates.

Let me know when it is done and then I will cherry-pick it to the 0.15 branch. Preferably at least one more native Turkish person would review the translation before it goes in. Do you know anybody who'd be interested? If not I can ask around.

**Comment by nuriu** [comment]
I don't know anybody actually. But you're right. Some words must pass through several people.

Do you know better tools than text editor for this kind of file? (I mean like poedit for po files.) I don't like & use transifex so any suggestions would be awesome. Also this could accelerate the translation & reviewing process.

**Comment by bjorn** [comment]
Ah, sure, the primary tool to edit such files would be Qt Linguist, which ships with Qt. It does some basic sanity checks on matching string parameters and punctuation, as well as doing suggestions based on already translated similar strings.

There is also an alternative to Transifex which I recently started trying out, called Weblate. If you want to give that a try just sign up there and you could probably request to translate Tiled here: https://hosted.weblate.org/projects/tiled/

**Comment by nuriu** [comment]
Qt Linguist then, thanks for help. I will update this PR.

**Comment by nuriu** [comment]
I think i finished first version of translations. After the new release i can review them one more time. (maybe for something like hotfix etc.)

**Comment by bjorn** [comment]
I've [asked on Twitter](https://twitter.com/thorbjorn81/status/701522323120201728) if anybody can help do a review of this new translation. I'll release a Tiled 0.15.2 as soon as it is in.

**Comment by nuriu** [comment]
This would be awesome, thanks by the way.

**Comment by bjorn** [comment]
Since nobody seems to be stepping up for a review, I just had a quick look myself to check if everything is alright. It seems to be mostly fine, but there are a number of strings marked as "complete" for which the translation is actually empty. I'm not sure of all the places, but most of the strings in "Tiled::Internal::MapDocumentActionHandler" context are affected. There's also English text in the Turkish translation fields for "Duplicate %n Object(s)" and "Remove %n Object(s)".

Please look into fixing this and maybe quickly go over everything again to make sure it's all alright. You have done an amazing job already, since I can imagine how much work it must be to start a new translation from scratch.

**Comment by nuriu** [comment]
I think I missed that one somehow. Sorry for that. I go over "Tiled::Internal::MapDocumentActionHandler" context and fixed it but didn't look others. Maybe later I will go over everything again.

**Comment by bjorn** [comment]
Alright, I'll have a quick look myself alter on and will merge it if I don't see further such problems. Thanks!

**Comment by bjorn** [comment]
I found a few more of these empty strings marked as finished:

* **MapReader**
    * Error reading embedded image for tile %1
    * Invalid (negative) tile id: %1
* **QObject** (all 4 strings)
* **QtColorPropertyManager** (all 4 strings)
* **Tiled::Internal::CommandDataModel** (all strings)
* **Tiled::Internal::NewTilesetDialog**
    * Failed to load tileset image &apos;%1&apos;.
    * No tiles found in the tileset image when using the given tile size, margin and spacing!
* **Tiled::Internal::PatreonDialog** (but it's alright to leave these out, since they're very long and somewhat personal, unless you feel confident writing a replacement)

**Comment by nuriu** [comment]
I have done all except Patreon one. There is a issue with that one because for example; "I'm already a patron!"; "patron" word of this sentence means "boss" in our language. So I can't figure out how to translate it.

**Comment by bjorn** [comment]
Thanks for the updates!

> There is a issue with that one because for example; "I'm already a patron!"; "patron" word of this sentence means "boss" in our language. So I can't figure out how to translate it.

While a patron and a boss both provide you with a living, the difference is that a boss tells you what to do while a patron supports the work you're already doing. In any case, the whole Patreon website is currently only available in English as far as I know so I think it's alright for this part to stay in English as well.

**Comment by bjorn** [comment]
Translation pushed in commit 92ef16ee6d09da51d8c0e2248894ff61cb736dc2. Also tagged the 0.15.2 release, so that'll be available later today. Thanks again!

**Pull request closed without merging**
