### PR TITLE
Scripting: Enabled creating images and using them

### PR DESCRIPTION
**Pull request by bjorn**
Now a script can create an image, either directly or by loading from a file or data or based on raw data. Then, the image can be passed to Tileset.loadFromImage or Tile.setImage.

Related to issue #2695

### CODE REVIEW

**Comment by bjorn** [comment]
@samhocevar I just finished this up and haven't gotten around to testing it nor documenting it, but this should give you quite a few options for getting image data into Tiled and setting it on tilesets or individual tiles, so hopefully it will help with porting your PICO-8 extension to JS.

With this change, images can be dynamically created from JS in three ways:

* Use `image.setPixel(x, y, index_or_rgb)` to set each pixel directly.
* Use `new Image(data, width, height, format)` to create an image from raw data, see the `Format` enum for the various supported arrangements.
* Use `image.loadFromData(data, format)` to load an image from data in a format like "png" or "bmp".

There are also the methods for modifying the palette.

**Comment by samhocevar** [comment]
For future reference, I provided feedback for this feature in https://github.com/bjorn/tiled/issues/2695#issuecomment-704405170 and resolved current conflicts for this PR in https://github.com/bjorn/tiled/pull/2906

**Comment by bjorn** [comment]
Thanks @samhocevar! Your help is really appreciated and I'll make sure to get around to reviewing this tomorrow.

I'll find out tomorrow but just a quick question, was there anything that stood out while resolving the conflicts? Because I'd prefer to rebase the change instead of merging. Not that it matters much because we can also squash when merging back to `master`.

**Comment by samhocevar** [comment]
Thanks for the reply! A rebase would be harmless; the conflicts just arose in `tiled.pro` and `tiled.qbs` because of the recent addition of `scriptfileinfo.cpp` which was too close to the `scriptfileimage.cpp` entry in the files.

**Comment by bjorn** [comment]
> * `Image.setColorTable(["#123abc"])` does not work properly, because `ScriptImage::setColorTable` explicitly casts the array elements to `UInt`. I have to do `Image.setColorTable([0xff123abc])` instead, which is OK but a bit inconsistent with _e.g._ `Tileset.backgroundColor` which accepts the `"#123abc"` argument.

I've fixed this in 9124a7c88881fbc6df8ae6bd919366c614cc928d.

> * calling `Tileset.loadFromImage()` before `Tileset.setTileSize()` does not work; the order matters here, otherwise Tiled tries to reload a non-existent image.

Yeah, I'm not quite how to handle this, including how to handle undo when setting the image this way, or saving. I guess in case of saving this could lead to storing the image embedded in the file. I'll need to look into this before it can be merged.

**Comment by bjorn** [comment]
@samhocevar For now I just documented that `Tileset.loadFromImage` needs to be called after `Tileset.setTileSize`, since it actually cuts up the image so it needs the tile size first. In addition, once the tileset contains tiles but has no "image" set on it, it is assumed to be a collection of images tileset and on such a tileset you're not allowed to set the tile size (because for such a tileset the tile size is automatically set to the largest tile in the set).

If there are any problems with the current API, please let me know!

**Comment by bjorn** [comment]
@samhocevar I noticed that you currently have the following code:

https://github.com/samhocevar/tiled-pico8/blob/9eb7529d1495988839989611754b72a3bbddced5/pico8.js#L97-L100

But this is the order which doesn't work, right?

**Pull request merged**
