### PR TITLE
Update support-for-tmx-maps.md

### PR DESCRIPTION
**Pull request by sausagejohnson**
Adding Orx Converter to the list of supported tools for Tiled.

### CODE REVIEW

**Comment by bjorn** [comment]
Looks fine, thanks!

**Comment by sausagejohnson** [comment]
Thanks, Bjorn. I noticed the change hasn't flowed to http://doc.mapeditor.org/reference/support-for-tmx-maps. Is there a periodical build for the documentation?

**Comment by bjorn** [comment]
> Is there a periodical build for the documentation?

Unfortunately there isn't at the moment. I've just pushed an update so now the change is live.

**Comment by bjorn** [comment]
@sausagejohnson Btw, did you consider adding an export plugin to Tiled instead? That should be easier to use than an external tool.

**Comment by sausagejohnson** [comment]
Thanks, Bjorn. I'd definitely consider doing an exporter if we get enough people wanting it. I'll certainly keep it in mind.

**Pull request merged**
