### PR TITLE
Jsonformat

### PR DESCRIPTION
**Pull request by saeedakhter**
Addresses issue https://github.com/bjorn/tiled/issues/1585

This introduces a new json revision (version: 1.2) that is much easier to serialize and de-serialize.  For an example of de-serializing the new format in Unity3d, see https://github.com/saeedakhter/TiledJsonUnity3d

**Problem:**
Tiles were serialized as a map with the tile ID as the key:
```
"tiles":
    {
     "0": { "image":"necro3_0\/5.png", "imageheight":32, "imagewidth":32 },
     "1": { "image":"necro3_0\/4.png", "imageheight":32, "imagewidth":32 }
    }
```
In Unity3d, this makes it difficult (impossible?) to use Unity3d's JSON deserialization:
https://docs.unity3d.com/Manual/JSONSerialization.html 

**Solution (this pull request):**
Serialize tiles and properties as a list.  If an ID is required, put it inside the list object.  Example:
```
 "tiles":[
        {
         "terrain":[0, 2, 2, 2],
         "tile":0
        }, 
        {
         "properties":[
                {
                 "name":"Prefrab",
                 "type":"string",
                 "value":"Floor*"
                }, 
                {
                 "name":"SortingLayer",
                 "type":"string",
                 "value":"Floor"
                }],
         "terrain":[0, 0, 0, 0],
         "tile":1
        }, 
```

### CODE REVIEW

**Comment by bjorn** [comment]
Thanks a lot for your work on this!

**Comment by bitinn** [comment]
Thx for your good work @saeedakhter!

Just wondering @bjorn, does the snapshot build contain this change? I was writing a parser on C# for my specific use-case and realize it would have been much easier with this updated as I just happen to heavily rely on tileset properties.

**Comment by bjorn** [comment]
@bitinn Yes, the changes are included in the [latest snapshot build](https://thorbjorn.itch.io/tiled/devlog/24167/multi-layer-editing-and-other-stuff). The [JSON format documentation](http://docs.mapeditor.org/en/latest/reference/json-map-format/) is also already updated, which means it's now actually time to host explicit "Tiled 1.1" documentation (probably as default) as well to avoid confusion.

**Comment by bitinn** [comment]
@bjorn fantastic! and yeah I was reading the doc and realize `tileproperties` was missing and find my way here :)

**Pull request merged**
