### PR TITLE
Add invokable coordinate conversion functions to MapItem

### PR DESCRIPTION
**Pull request by mitchcurtis**

### CODE REVIEW

**Comment by bjorn** [comment]
Looks good! :-)

**Comment by bjorn** [comment]
Will you add a little hover coordinate display to Tiled Quick now?

**Comment by mitchcurtis** [comment]
> Will you add a little hover coordinate display to Tiled Quick now?

Haha, I'm currently writing some tests to ensure that the coordinate mapping is correct. I could definitely add it after that. :)

**Comment by mitchcurtis** [comment]
By the way, I'm guessing we have to support Qt Quick 2.4 since the minimum Qt version supported is 5.4?

**Comment by bjorn** [comment]
> By the way, I'm guessing we have to support Qt Quick 2.4 since the minimum Qt version supported is 5.4?

Yes, unless there is some reason to depend on a more recent version?

**Comment by mitchcurtis** [comment]
Nope, just wanted to make sure.

**Pull request merged**
