### PR TITLE
use QHash instead of QList for Document::sDocumentInstances

### PR DESCRIPTION
**Pull request by oncer**
See issue #2156

### CODE REVIEW

**Comment by bjorn** [comment]
Thanks for this optimization!

I've pushed some improvements based on https://github.com/bjorn/tiled/issues/2156#issuecomment-511937254, though I did not have time to test it. Can you help with testing the change?

**Comment by bjorn** [comment]
At least I could have made sure it compiles... :-)

**Comment by oncer** [comment]
It compiles for me, and works well for my use-case. I can confirm there is another performance boost when using the cached canonical path.

**Comment by bjorn** [comment]
Yeah, it didn't compile when I first pushed my commit, but I force-pushed a working change after the CI system told me about the problem. :-)

You're welcome and thanks again for bringing this up!

**Pull request merged**
