### PR TITLE
Tileset offset and Layer offset now considered when drawing with libtiled-java

### PR DESCRIPTION
**Pull request by digitalhoax**
Fix for orthogonal and isometric view.

### CODE REVIEW

**Comment by bjorn** [comment]
Would there be any way around all these `null` checks? They make the whole thing very verbose.

Otherwise this change looks fine me. Do you have anything to add, @mikepthomas?

**Comment by mikepthomas** [comment]
I'm sure you can set the default value to zero using the jaxb commons [defaut-value-plugin](https://github.com/javaee/jaxb2-commons/tree/master/default-value-plugin) rather than having to do all the null checking... would need to take a closer look though to be sure :)

**Comment by bjorn** [comment]
Ah, that stuff makes me dizzy. :-(

I'll just accept this patch as-is for now, anyway.

**Comment by bjorn** [comment]
Thanks, @digitalhoax!

**Pull request merged**
