### PR TITLE
tiledquick: allow qrc-based tileset images

### PR DESCRIPTION
**Pull request by mitchcurtis**
A similar change was done a while ago in a1ceb57e, but the code has
changed a lot since then, so it needs to be updated.

### CODE REVIEW

**Comment by mitchcurtis** [comment]
Will compile without https://github.com/bjorn/tiled/pull/1947, but requires it in order to work correctly. Am I able to push merge commits (to merge master into wip/qtquick)?

**Comment by bjorn** [comment]
> Am I able to push merge commits (to merge master into wip/qtquick)?

I guess you could include them in the PR, but I'd prefer to just push a merge myself.

**Comment by mitchcurtis** [comment]
This could be merged now I think.

**Comment by bjorn** [comment]
Yes, master was merged and this looks fine, thanks!

**Pull request merged**
