### PR TITLE
Added Korean Translation

### PR DESCRIPTION
**Pull request by miru2533**
Our team made the complete Korean translation for Tiled!
It's our first PR, so please excuse if there is some mistake :)

### CODE REVIEW

**Comment by bjorn** [comment]
That's great, I'll have a look at it soon!

At quick glance I noticed only one mistake, please delete the `examples/sticker-knight/map/Thumbs.db` file again, as this should not be added to the repository.

**Comment by miru2533** [comment]
Oh, I didn't recognize it.
I deleted that one.

**Comment by bjorn** [comment]
It is alright if I squash all the commits? Am I correct that the translation was effectively done by @miru2533 and @SshipSunBee?

**Comment by miru2533** [comment]
Yes, it was done by two people and squashing is OK!

**Comment by bjorn** [comment]
Thanks a lot! I've added you to the `AUTHORS` file in 8e6fb74cd801b203e6356398bd8b782a66930bd0.

**Comment by devAdaid** [comment]
I understood. We will consider translating later! Thanks for mentioning :)

**Pull request merged**
