### PR TITLE
Fixed install of manpages

### PR DESCRIPTION
**Pull request by Ablu**

### CODE REVIEW

**Comment by bjorn** [comment]
Ouch, I somehow missed those. I've cherry-picked this to the 0.12 branch as commit 1cddb07. Thanks!

**Comment by Ablu** [comment]
Ah. sorry opened against the wrong branch.

If you merge it master I have a (kind of) daily builds (it would trigger builds as long as my pc is online once a day) for fedora. It builds in a new copr at https://copr.fedoraproject.org/coprs/ablu/tiled-dailies/. Should I add that to the daily build section on the website? (The builds are done online, I only automatically prepare a .src.rpm using scripts from https://github.com/Ablu/tiled-rpm-dailies and upload it for copr). Though you won't be able to trigger builds there since it requires a fedora maintainer membership.

**Comment by bjorn** [comment]
@Ablu Well, I'm fine with adding the link there as long as you maintain this service, thanks! I've pushed the link in bjorn/tiled-website@73c8356.

**Comment by bjorn** [comment]
Sorry @Ablu, actually I cherry-picked it to the wrong branch. I somehow thought I moved the man pages in the release, but I did that on master only recently so that's also where this change should go... I forced-pushed the commit away from 0.12, hoping this won't cause anybody issues.

**Comment by bjorn** [comment]
Erm, oh crap I realized now that I had already merged it to master. Oh well, revert commit it is.

**Pull request merged**
