### PR TITLE
UPDATE - Translation to the Brazilian Portuguese language.

### PR DESCRIPTION
**Pull request by laetemn**
New update of the translation to the Brazilian Portuguese language.

### CODE REVIEW

**Comment by bjorn** [comment]
Thanks a lot for all the updates, great work!

**Comment by bjorn** [comment]
Why did you close this pull request?

**Comment by laetemn** [comment]
I am making the necessary corrections.

The texts for translation of the buttons in dialog boxes do not exist?

**Comment by bjorn** [comment]
> The texts for translation of the buttons in dialog boxes do not exist?

Those texts come from Qt so a Brazilian Portuguese translation of Qt would be necessary. If it doesn't exist, maybe we can ship one that just translates those strings showing up in Tiled.

**Comment by laetemn** [comment]
I would like to have these texts to translate.
At the moment, these are the only texts that are not translated into Brazilian Portuguese language.

**Comment by bjorn** [comment]
Would it help to try falling back to Portuguese for those texts?

**Comment by laetemn** [comment]
I searched the texts of the buttons using the software "Qt Creator (Community)", however, not find the necessary references.

cancel

**Comment by bjorn** [comment]
> I searched the texts of the buttons using the software "Qt Creator (Community)", however, not find the necessary references.

They are texts from Qt, not from Qt Creator.

**Comment by bjorn** [comment]
Why did you decide to keep the %n in the singular case for the texts with plural forms?

**Comment by laetemn** [comment]
Removed the expression '% n' phrases.

**Comment by bjorn** [comment]
Closing this since it seems replaced by #1112.

**Pull request closed without merging**
