### PR TITLE
Suppress unsupported attribute warnings in libtiled-java

### PR DESCRIPTION
**Pull request by mikepthomas**
I have added color to the ObjectGroup class to suppress unsupported attribute warning to suppress unsupported attribute warning when loading map to fix issue #124 

When saving the sewers.tmx file using Tiled v0.17.0 the width and height are no longer saved to the ObjectGroup tag so I have not added these... should they be added too to support backwards compatibility with older formats?

### CODE REVIEW

**Comment by bjorn** [comment]
I find it a bit strange to have a `setColor` taking a `String` and a `getColor` returning a `Color`. Would there be any way around this? Probably the fact that the map reader is based on reflection is causing problems here? (I'd like to rip out the reflection code)

**Comment by bjorn** [comment]
> When saving the sewers.tmx file using Tiled v0.17.0 the width and height are no longer saved to the ObjectGroup tag so I have not added these... should they be added too to support backwards compatibility with older formats?

No. It would again be needed because of the reflection, right? When width/height are still present in a TMX file for objectgroup, they should simply be ignored.

**Comment by mikepthomas** [comment]
Sorry @bjorn Ive made a bit of a mess of this pull request, Ive closed and will raise another

**Comment by bjorn** [comment]
@mikepthomas No problem, but just note that you can always force-push (`git push -f ...`) to the branch that you opened the pull request for, after doing the cleanup. I see you even re-forked Tiled, but there is really no need for that.

**Pull request closed without merging**
