### PR TITLE
add link to tmxlite C++ parser

### LINKED ISSUE #1397: tmxlite c++ parser
I'd like to submit another parsing library - this one aims to be lightweight by not requiring any external libraries when building (no boost, no zlib), whilst still supporting compressed map files:

https://github.com/fallahn/tmxlite

### PR DESCRIPTION
**Pull request by fallahn**
closes #1397

### CODE REVIEW

**Comment by bjorn** [comment]
Hey @fallahn, thanks for the PR! I'm sorry that I didn't get around this myself, the e-mail about the issue you had opened some months back must have gotten buried in my inbox. :-(

**Comment by fallahn** [comment]
Thanks for accepting it, and thanks for a great piece of software!

**Comment by bjorn** [comment]
You're welcome!

**Comment by bjorn** [comment]
Just a heads up, the link hasn't make it onto the live page yet because an upgrade to `mkdocs` broke the site generation. I'll need to find some time to fix up the global header bar in a new theme before I can push an update.

**Comment by fallahn** [comment]
No worries, thanks for the update :)

**Pull request merged**
