### PR TITLE
#1310: Multiple Frame Duration Editing

### PR DESCRIPTION
**Pull request by Alturos**
It's late, and I didn't give this a hard pass for styling yet, but it works. Will check over it once more in the morning, but wanted to get it up now.

### CODE REVIEW

**Comment by bjorn** [comment]
Looks like a good start.

Btw, please try to get rid of all the merge commits. You should rebase your change on my master branch instead.

**Comment by Alturos** [comment]
Sorry, will do. Will also investigate these build issues. But, tomorrow! It's bed time. :sleeping:

**Comment by bjorn** [comment]
The Travis CI build issues are because Travis compiles with qmake on Linux, where the precompiled header is not used. This causes it to be missing an include for `QItemSelection`.

**Comment by dorkster** [comment]
I'd like to see this get merged, but it looks like it's been abandoned. I [fixed the merge conflicts and missing include](https://github.com/bjorn/tiled/compare/master...dorkster:AnimationEditor). Should I open a pull request?

**Comment by bjorn** [comment]
@dorkster Did you compare this to #1784? I think that may be a better candidate for this functionality, but it also has some work outstanding (though only since 5 days).

**Comment by dorkster** [comment]
@bjorn I missed that one. You're right, I think #1784 is a better implementation of this feature.

**Pull request closed without merging**
