### PR TITLE
Avoid Inf values in scaling factors

### PR DESCRIPTION
**Pull request by Carisius**
This solves #1016 and #981 issues

### CODE REVIEW

**Comment by Carisius** [comment]
What do you think about this patch? The nan values come when any coordinate of startDiff is 0 (small change?) and dividing by 0 makes that coord of scalingFactor become Inf then other operation on that Inf value, maybe multiplying by 0 is from where the nan comes. I've noticed there is another float division not checked in the same file, in updateResizingItems, I've not changed that one. This patch only avoids odd values result of division by zero with float numbers because those divisions are unchecked. It works, solving the mentioned issues though maybe it would be better to hide the extra sizers as tryed #982, well or maybe not.

**Comment by bjorn** [comment]
Sorry I still need to find some time to review this and consider the options, but I certainly plan do it before releasing Tiled 0.13. Thanks in any case for looking into this!

**Comment by bjorn** [comment]
I think the fix is a good start, but I'll lower the limit a little to avoid preventing resize too soon and I'll apply it also to the case of resizing multiple items, since the same problem exists there.

**Comment by bjorn** [comment]
I decided to do it slightly differently, by checking the values afterwards, see commit a927db8.

Let me know if you see any problems with that approach.

**Pull request merged**
