### PR TITLE
Loading Objecttypes.xml with default properties

### PR DESCRIPTION
**Pull request by dazKind**
Related to the following issues, maybe even more: #365 #392 #367

Allows loading of objecttypes with default properties from xml.

Test-data: [objecttypes.xml for Stendhal entities](http://arianne.cvs.sourceforge.net/viewvc/arianne/stendhal/tiled/objecttypes.xml?content-type=text%2Fplain) by @nhnb

### CODE REVIEW

**Comment by dazKind** [comment]
It works, but it's still a bit rough around the edges, namely:
 - No gui yet. Use the Preferences->Objecttypes->Import button to load the xml. The path to this xml will persist in the registry. If a valid path is found at startup the file will be loaded. **Im not a Qt pro, so I'll welcome any help with the gui-editor to replace the old gui with a more simpler new one**
 - when assigning a new type to an object the properties will be added as soon as you deselect the object in the editor. **Review proper callbacks for editing the type-field**

**Comment by lazybotter** [comment]
Has this been added to v0.15.1 yet?

**Comment by bjorn** [comment]
@lazybotter No, but I'll make sure to have a close look at it for the next feature release. It should go well together with #1131.

**Comment by lazybotter** [comment]
That's great, do you have an estimated time for the update? How much coffee would I have to buy you to get this done asap? 😜

**Comment by bjorn** [comment]
> That's great, do you have an estimated time for the update? How much coffee would I have to buy you to get this done asap?

I estimate Tiled 1.0 could release in April, but note that last year I thought I could still do it by December. If this pull request should be in soon, the best I can do is give it priority over other things, then it could be in the daily builds in 1-2 weeks (because I can currently afford to work on Tiled one day/week).

The best way to support Tiled development is to [become a patron on Patreon](https://www.patreon.com/bjorn?ty=h). There you can support me for however long you want at whatever level is comfortable to you. I'm certainly more likely to prioritize features when they are requested by patrons. :-)

**Comment by dazKind** [comment]
Nice to see this PR getting some traction! :+1:

**Comment by bjorn** [comment]
So, this is a very good start and I'd like to merge it into master. However, it can't be merged without finishing the configuration UI (at the very least a "choose file" option to replace the currently no longer functional object types table). Also the code should be cleanup up a little from comments and debug outputs.

@dazKind Will you have time to do these things?

**Comment by bjorn** [comment]
Just a heads up, I'm working right now on a new object types editor that is not part of the preferences. It got a little too much functionality to remain in the preferences, with this file backend and the custom properties added. Still, it would be nice if you could rebase your patches to master in the meantime.

**Comment by lazybotter** [comment]
That's fantastic! Great stuff!

**Comment by bjorn** [comment]
I've made some progress on the configuration UI today. Here's a screenshot of the new object types editor:

object types editor tiled_074

There are however quite a few issues remaining before I can submit this. For the object types editor:

* Update properties view when switching object type definition files
* Don't focus the property value for editing when renaming a property
* Sort out the question of multi-selection regarding the property view
* Change the text of the "Save" button when choosing the objecttypes.xml file, maybe to "Choose" / "Choose File"
* Consider whether to merge the object type definitions when "Import" is used. Currently it replaces existing list of types.

And for the Tiled main window:

* Update the properties view for the selected object when editing its type
* Disallow removing/renaming of predefined custom properties

**Comment by dazKind** [comment]
@bjorn Sry, I'm afraid I dont have the time to help you out

**Comment by dazKind** [comment]
Awesome! Good work :)

**Comment by bjorn** [comment]
@dazKind Thanks man. It only took me about 12 hours to finish it, but I think it was worth it! Unfortunately, there are still things remaining that I'd like to improve and there's still an issue with initial creation of the objecttypes.xml file, since I forgot to add some code that creates its directory when necessary. You can watch and listen to me working on the remaining issues on [livecoding.tv](https://www.livecoding.tv/bjorn/videos/) (part 22-25).

Also, this change goes really well together with #1131, which is now merged as well!

**Pull request merged**
